proxy:
  image: proxy:0.1
  links:
    - identidock
  ports:
    - "80:80"
  environment:
    - NGINX_HOST=zhoujiaming
    - NGINX_PROXY=http://identidock:9090

identidock:
  build: .
  links:
    - dnmonster
    - redis
  environment:
    ENV: PROD

dnmonster:
  image: amouat/dnmonster:1.0

redis:
  image: redis:3.0
