
jenkins:
  build: .
  ports:
    - "8080:8080"
    - "50000:50000"
  volumes:
    - "/var/run/docker.sock:/var/run/docker.sock"
  volumes_from:
    - jenkins-data:rw
  links:
    - jenkins-data

jenkins-data:
  build: .

