---
- hosts: identidock
  remote_user: jiaming
  sudo: yes
  tasks:
  - name: install setuptools for easy_install

    apt:
      name: python-setuptools
      state: present


  - name: pip
    easy_install: name=pip
  - name: docker-py
    pip: name=docker-py
  - name: redis container
    docker_container:
      name: redis
      image: redis:3.0
      pull: yes
      state: started
      restart_policy: always
  - name: dnmonster container
    docker_container:
      name: dnmonster
      image: amouat/dnmonster:1.0
      pull: yes
      state: started
      restart_policy: always
  - name: identidock container
    docker_container:
      name: identidock
      image: amouat/identidock:1.0
      pull: yes
      state: started
      links:
        - "dnmonster:dnmonster"
        - "redis:redis"
      env:
        ENV: PROD
      restart_policy: always
  - name: proxy container
    docker_container:
      name: proxy
      image: amouat/proxy:1.0
      pull: yes
      state: started
      links:
        - "identidock:identidock"
      ports:
        - "80:80"
      env:
        NGINX_HOST: www.identidock.com
        NGINX_PROXY: http://identidock:9090
      restart_policy: always
